### ISSUE TITLE
CMake-external-project integration may not work for C projects

### ISSUE THREAD

**Issue by andreasbuhr** [amzn/hawktracer#70]
It seems to me the cmake-external-project integration only works with C++ projects. With a C project, I get linker errors like

`event_id_provider.cpp:(.text+0x1c): undefined reference to `__cxa_guard_acquire'`

To reproduce, take this example project, rename the main.cpp to main.c, change CMakeLists.txt to reflect this change and build. 
https://github.com/amzn/hawktracer/tree/f0c28d2f525a3674526d231e363de368f2a67b0e/examples/integrations/cmake-external-project

For an easy solution, I'd suggest to add an option to hawktracer.cmake. There is already an option to create a static build.
https://github.com/amzn/hawktracer/blob/f0c28d2f525a3674526d231e363de368f2a67b0e/examples/integrations/cmake-external-project/hawktracer.cmake#L7

Or is there already a solution I have missed?

**Comment by loganek** [comment]
@andreasbuhr thanks for the report.
The build is failing because the application is not being linked to standard c++ library. There are 2 potential fixes for that:
* set `HT_BUILD_STATIC` to `OFF` so the library is not needed for linking and is only needed for runtime
* link the example with libstdc++:
```
target_link_libraries(cmake-external-project hawktracer stdc++)
```

This is by design and I don't think we should be changing anything in HawkTracer. However, I think it'd be good to document above solutions in the code in case somebody experiences similar problems. I'll open a pull request for that soon.

**Comment by andreasbuhr** [comment]
Thanks a lot for looking into this and providing two solutions. I somehow assumed that HawkTracer would work with pure C projects, without any C++ involved anywhere.
Thanks again, I'll go ahead and close this issue.

**Comment by loganek** [comment]
OK, I think I've misunderstood you. HawkTracer indeed can be compiled just using the C compiler, however, that method is only supported when compiling the amalgamated `hawktracer.c` file.
The reason why it's not possible to do it with CMake, is because some of the C code is written in .cpp file and ifdef'ed for C++ (e.g. `global_timeline.cpp`) - the extension makes CMake think that this is C++ file, and it uses C++ compiler for building it.

I think having some kind of flag like `FORCE_C` as you suggested in the first comment would actually make sense, and that could be implemented using [LANGUAGE](https://cmake.org/cmake/help/v3.3/prop_sf/LANGUAGE.html) CMake source file property.

I'll re-open the ticket and will try to implement that flag when I have time as I think it's actually nice addition (or feel free to raise a pull request if it's something you'd like to contribute to :)

**Comment by loganek** [comment]
I've addressed the problem in https://github.com/amzn/hawktracer/commit/722607722cbb3edd86d0363b22995303ea6e1378
I added `FORCE_C_COMPILATION` flag so when it's set to `ON`, cmake uses C compiler.

@andreasbuhr feel free to re-open the issue if you have any other questions regarding this feature.
